// README source file

:travisCi: https://travis-ci.com/pmorou/quantasma
:examplesDir: quantasma-examples/src/main/java/quantasma/examples
:ta4jLink: https://github.com/ta4j/ta4j

// below line solves eating first rendered line by converters
***

= Quantasma image:{travisCi}.svg?branch=master["Build Status", link="{travisCi}"]

All-in-one algorithmic trading platform. Build your own backtested-strategy using Java, and execute along with support of continuous track and optimization mechanics.

Modules:

* link:{quantasma-app/}[quantasma-app]: ready-to-use application based on below modules
* link:{quantasma-core/}[quantasma-core]: trading library providing core mechanics
* link:{quantasma-examples/}[quantasma-examples]: example usages
* link:{quantasma-integrations/}[quantasma-integrations]: integrations with 3rd party APIs

*NOTE: Provided modules might solve your problems, however, they are still in development. Use at your own risk.*

These solutions at its core stands on top of the modern technical analysis library link:{ta4jLink}[ta4j] providing many additional features as:

* generic bar implementations, eg. BID and ASK prices
* user-defined multi-period time series
* flexible market-aware strategies
* programmable parametrized backtests

The aim is to provide any needed functionality to follow the ever-changing markets in the most efficient way.

= Getting Started

Maven repository support soon. Right now fork/clone this repository and start using anything you need.

== Requirements

>= Java 9

Upgrade to Java 10 is comming soon.

Before project compilation few dependencies must be installed, it can be done through script.

[source]
----
./scripts/install_dependencies.sh
----

Compilation should run now smoothly.

[source]
----
mvn clean compile
----

== Example Usage

In case you decide to create your own trading application its as simple as the following code.

[source,java,indent=0]
----
include::{examplesDir}/TradeAppExample.java[tags=tradeAppExample]
----

Backtest parametrization:

[source,java,indent=0]
----
include::{examplesDir}/ParametrizedBacktestExample.java[tags=parametrizedBacktestExample]
----
