server:
  port: 8080

service:
  historical-data:
    enabled: false
    prefix: dukascopy
  live-data:
    enabled: false
  backtest:
    enabled: false

spring:
  data:
    mongodb:
      host: ${HISTORICAL_DATA_MONGO_DB_HOST:localhost}
      port: ${HISTORICAL_DATA_MONGO_DB_PORT:12345}
      database: ${HISTORICAL_DATA_MONGO_DB_NAME:nonEmpty}
  profiles:
    active: mock

---

spring:
  profiles: mock
service:
  historical-data:
    prefix: mock
