server:
  port: 8080

service:
  historical-data:
    enabled: false
    prefix: mock
  live-data:
    enabled: false
  backtest:
    enabled: false

spring:
  data:
    mongodb:
      host: ${HISTORICAL_DATA_MONGO_DB_HOST:localhost}
      port: ${HISTORICAL_DATA_MONGO_DB_PORT:12345}
      database: ${HISTORICAL_DATA_MONGO_DB_NAME:nonEmpty}
  profiles:
    active: mock
  devtools:
    remote:
      secret: =YOUR_SECRET=
  datasource:
    url: jdbc:postgresql://${GENERAL_DATA_PG_HOST:}:${GENERAL_DATA_PG_PORT:}/
    name: ${GENERAL_DATA_PG_DB_NAME:}
    username: ${GENERAL_DATA_PG_USER:}
    password:
    initialization-mode: always

---

spring:
  profiles: mock
  datasource:
    url: jdbc:h2:mem:test
    name: test
    username: test
service:
  historical-data:
    prefix: mock

---

spring:
  profiles: dukascopy
service:
  historical-data:
    prefix: dukascopy
live:
  data:
    provider:
      url: =PLATFORM_URL=
      userName: =YOUR_USER_NAME=
      password: =YOUR_PASSWORD=
