server:
  port: 8080

service:
  historical-data:
    enabled: false
    prefix: mock
  live-data:
    enabled: false
  backtest:
    enabled: false

logging:
  level:
    root: INFO
    org.jooq: DEBUG

jooq:
  gen-container:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres

spring:
  data:
    mongodb:
      host: ${HISTORICAL_DATA_MONGO_DB_HOST:localhost}
      port: ${HISTORICAL_DATA_MONGO_DB_PORT:12345}
      database: ${HISTORICAL_DATA_MONGO_DB_NAME:nonEmpty}
  profiles:
    active: mock
  devtools:
    remote:
      secret: =YOUR_SECRET=
  datasource:
    url: jdbc:postgresql://${GENERAL_DATA_PG_HOST:}:${GENERAL_DATA_PG_PORT:}/
    name: ${GENERAL_DATA_PG_DB_NAME:}
    username: ${GENERAL_DATA_PG_USER:}
    password:
