spring:
  profiles: mock
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    name: test
    username: test
    initialization-mode: never
service:
  historical-data:
    prefix: mock
