version: '3'

services:
  historical-data-mongo-db:
    image: mongo
    volumes:
      - historical-mongo-db-vol:/app
    ports:
      - 27017:27017
    restart: always

  quantasma-app:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dukascopy
      - HISTORICAL_DATA_MONGO_DB_HOST=historical-data-mongo-db
      - HISTORICAL_DATA_MONGO_DB_PORT=27017
      - HISTORICAL_DATA_MONGO_DB_NAME=historical
    depends_on:
      - historical-data-mongo-db

volumes:
  historical-mongo-db-vol:
